package kconfig

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
)

const actionPlanCheckpointSchema = "linux-action-plan-checkpoint-v4"

// ActionPlanCheckpointBindings must come from the current planner invocation,
// not from the checkpoint being read. SourceArtifacts names declared source
// inputs; their physical roots may change between executions. ChoiceDialect
// comes from the current selected scripts/kconfig/symbol.c, even when both
// dialects produce identical resolved config values. ConfigFiles is the
// independently resolved config projection used by the family replay gate.
// The producer and consumer actions must declare the same source/config/tool
// inputs. A checkpoint is an intermediate action output, not a source of new
// authority for scanner reads, compiler capabilities or generated bytes.
type ActionPlanCheckpointBindings struct {
	VirtualSourceRoots                                                                 map[string]string
	Variant                                                                            string
	SourceArtifacts                                                                    map[string]string
	Toolsets                                                                           map[string]string
	ConfigValues                                                                       map[string]string
	ConfigFiles                                                                        map[string]string
	ConfigSymbolUniverse                                                               []string
	ChoiceDialect                                                                      ChoiceDialect
	HostPkgConfigManifestIdentity                                                      string
	ActionContracts                                                                    map[KbuildActionRoleRef]CompactKbuildActionContract
	ActionRoles                                                                        []KbuildActionRoleRef
	SourceNamespaces, SourceNamespacePrefixes, ExactSourceNamespaces, ExactSourcePaths map[string]string
}

// NewActionPlanCheckpointBindings derives current metadata using the same
// normalization as fresh Make-based construction, without evaluating Make.
func NewActionPlanCheckpointBindings(variant string, sourceArtifacts, toolsets, configFiles map[string]string, resolved *ResolvedConfig, choiceDialect ChoiceDialect, options CompactMetadataOptions, hostPkgConfigManifestIdentity string) (ActionPlanCheckpointBindings, error) {
	if resolved == nil {
		return ActionPlanCheckpointBindings{}, fmt.Errorf("checkpoint binding requires current resolved Kconfig")
	}
	roles, err := normalizeActionRoles(options.ActionRoles)
	if err != nil {
		return ActionPlanCheckpointBindings{}, err
	}
	contracts, err := normalizeCompactKbuildActionContracts(roles, options.ActionContracts)
	if err != nil {
		return ActionPlanCheckpointBindings{}, err
	}
	m := &CompactMetadata{sourceNamespaces: maps.Clone(options.SourceNamespaces), exactSourceNamespaces: maps.Clone(options.ExactSourceNamespaces)}
	if err := m.ensureActionPlanSourceNamespaceIndex(); err != nil {
		return ActionPlanCheckpointBindings{}, err
	}
	b := ActionPlanCheckpointBindings{Variant: variant, SourceArtifacts: maps.Clone(sourceArtifacts), Toolsets: maps.Clone(toolsets), ConfigValues: resolvedConfigFragment(resolved), ConfigFiles: maps.Clone(configFiles), ChoiceDialect: choiceDialect, ActionRoles: roles, ActionContracts: contracts, HostPkgConfigManifestIdentity: hostPkgConfigManifestIdentity,
		SourceNamespaces: m.sourceNamespaces, SourceNamespacePrefixes: m.sourceNamespacePrefixes, ExactSourceNamespaces: m.exactSourceNamespaces, ExactSourcePaths: m.exactSourcePaths}
	for key := range resolved.Effective {
		if isConfigKey(key) {
			b.ConfigSymbolUniverse = append(b.ConfigSymbolUniverse, key)
		}
	}
	slices.Sort(b.ConfigSymbolUniverse)
	return b, b.validate()
}

// BindActionPlanCheckpoint restores only runtime compiler bridges. Its metadata
// result is used by the current supplemental guard coordinator, never by Make.
func (s *KbuildProbeScopes) BindActionPlanCheckpoint(plan *ActionPlan) (*CompactMetadata, error) {
	if plan == nil || plan.metadata == nil || plan.selectionGraph == nil {
		return nil, fmt.Errorf("compiler scope binding requires a restored checkpoint")
	}
	if err := s.BindActionPlanToolsetPathCapabilities(plan.metadata); err != nil {
		return nil, err
	}
	return plan.metadata, nil
}

type planCheckpointRoot struct {
	Artifact, Path string
	Virtual        bool
}
type planCheckpointContract struct {
	Role     KbuildActionRoleRef
	Contract CompactKbuildActionContract
}
type planCheckpointOutput struct {
	Producer string
	Slot     int
	Value    bool
}
type actionPlanCheckpoint struct {
	VirtualSourceRoots            map[string]string
	Schema, Variant               string
	SourceArtifacts               []string
	Plan                          *ActionPlan
	Graph                         planCheckpointSelectionGraph
	Roots                         map[string]map[string]planCheckpointRoot
	Profiles                      []string
	ConfigValues, ConfigFiles     map[string]string
	ConfigSymbolUniverse          []string
	ChoiceDialect                 ChoiceDialect
	HostPkgConfigManifestIdentity string
	Contracts                     []planCheckpointContract
	Roles                         []KbuildActionRoleRef
	SourceNamespaces              map[string]string
	SourceNamespacePrefixes       map[string]string
	ExactSourceNamespaces         map[string]string
	ExactSourcePaths              map[string]string
	CompilerInvocations           map[string]actionRecipeCompilerProbeInvocation
	CompoundCompilerProbes        map[string][]actionRecipeCompoundCompilerProbe
	ProjectedValidations          []string
	ExecutionCheckRoots           []string
	ProjectedInternalNodes        map[string]bool
	ProjectedInternalOutputs      []planCheckpointOutput
	ProjectedOriginalOutputs      map[string]projectedGeneratorOriginalOutputCommitment
}

func (b ActionPlanCheckpointBindings) validate() error {
	if err := validatePlanName("checkpoint variant", b.Variant); err != nil {
		return err
	}
	if len(b.SourceArtifacts) == 0 || b.ConfigValues == nil || b.ConfigFiles == nil || b.ActionContracts == nil {
		return fmt.Errorf("checkpoint requires current source/config/action bindings")
	}
	if b.ChoiceDialect != ChoiceDialectParent && b.ChoiceDialect != ChoiceDialectMember {
		return fmt.Errorf("checkpoint requires a supported current choice dialect, got %d", b.ChoiceDialect)
	}
	for name, root := range b.SourceArtifacts {
		if name == "" || !filepath.IsAbs(root) || filepath.Clean(root) != root {
			return fmt.Errorf("invalid checkpoint source binding %q", name)
		}
	}
	if len(b.Toolsets) != 2 {
		return fmt.Errorf("checkpoint requires current target and host toolsets")
	}
	for name, root := range b.VirtualSourceRoots {
		if name != root || !fs.ValidPath(root) || strings.ContainsAny(root, "\\\x00") {
			return fmt.Errorf("invalid checkpoint virtual source binding %q", name)
		}
	}
	for _, scope := range []string{"target", "host"} {
		if err := validateProbeIdentity(b.Toolsets[scope]); err != nil {
			return err
		}
	}
	if value := b.HostPkgConfigManifestIdentity; value != "" {
		if !strings.HasPrefix(value, "sha256-") || len(value) != len("sha256-")+64 {
			return fmt.Errorf("invalid checkpoint host pkg-config manifest identity")
		}
		for _, digit := range value[len("sha256-"):] {
			if digit < '0' || digit > '9' {
				if digit < 'a' || digit > 'f' {
					return fmt.Errorf("invalid checkpoint host pkg-config manifest identity")
				}
			}
		}
	}
	return nil
}

// CaptureActionPlanCheckpoint freezes a fully lowered provisional plan before
// source analysis or content addressing mutates it. Compiler request/expression
// state is captured separately after initial discovery is complete. No scanner
// receipts, result oracles or lazy Make state cross this boundary.
func CaptureActionPlanCheckpoint(plan *ActionPlan, bindings ActionPlanCheckpointBindings) ([]byte, error) {
	if err := bindings.validate(); err != nil {
		return nil, err
	}
	if plan == nil || plan.metadata == nil || plan.selectionGraph == nil || plan.probeDiscoveryOnly || len(plan.projectedGeneratorCandidates) != 0 {
		return nil, fmt.Errorf("checkpoint requires complete concrete lowering and projected-generator preparation")
	}
	if err := plan.exportReachableActionPlanInputSets(); err != nil {
		return nil, err
	}
	m := plan.metadata
	r := actionPlanCheckpoint{
		VirtualSourceRoots: maps.Clone(bindings.VirtualSourceRoots),
		Schema:             actionPlanCheckpointSchema, Variant: bindings.Variant,
		ChoiceDialect:                 bindings.ChoiceDialect,
		HostPkgConfigManifestIdentity: bindings.HostPkgConfigManifestIdentity,
		SourceArtifacts:               slices.Sorted(maps.Keys(bindings.SourceArtifacts)),
		Plan:                          plan, Graph: capturePlanCheckpointGraph(plan.selectionGraph), Roots: map[string]map[string]planCheckpointRoot{},
		ConfigValues: m.configFragment, ConfigFiles: bindings.ConfigFiles, ConfigSymbolUniverse: m.configSymbolUniverse,
		SourceNamespaces: m.sourceNamespaces, SourceNamespacePrefixes: m.sourceNamespacePrefixes,
		ExactSourceNamespaces: m.exactSourceNamespaces, ExactSourcePaths: m.exactSourcePaths,
		CompilerInvocations: plan.compilerProbeInvocations, CompoundCompilerProbes: plan.compoundCompilerProbes,
		ProjectedValidations: plan.projectedGeneratorValidations, ProjectedInternalNodes: plan.projectedGeneratorInternalNodes,
		ExecutionCheckRoots:      slices.Clone(plan.executionCheckRoots),
		ProjectedOriginalOutputs: plan.projectedGeneratorOriginalOutputs,
	}
	for _, profile := range m.Config.KbuildProfiles {
		r.Profiles = append(r.Profiles, profile.Name)
	}
	r.Roles = m.actionRoles
	roles := slices.SortedFunc(maps.Keys(m.actionContracts), func(a, b KbuildActionRoleRef) int {
		if c := strings.Compare(a.Scope, b.Scope); c != 0 {
			return c
		}
		return strings.Compare(a.Role, b.Role)
	})
	for _, role := range roles {
		r.Contracts = append(r.Contracts, planCheckpointContract{role, m.actionContracts[role]})
	}
	// Preserve every configured contract, including roles not used by this
	// particular config. Missing or extra contracts are not inferred on restore.
	physicalRoots := map[string]string{}
	for profile, entry := range r.Graph.Profiles {
		r.Roots[profile] = map[string]planCheckpointRoot{}
		for logical, physical := range entry.Roots {
			if virtual, ok := bindings.VirtualSourceRoots[logical]; ok && virtual == physical {
				r.Roots[profile][logical] = planCheckpointRoot{Artifact: logical, Path: ".", Virtual: true}
				continue
			}
			canonical, ok := physicalRoots[physical]
			if !ok {
				var err error
				canonical, err = filepath.Abs(physical)
				if err != nil {
					return nil, err
				}
				canonical, err = filepath.EvalSymlinks(canonical)
				if err != nil {
					return nil, fmt.Errorf("checkpoint source root %q: %w", logical, err)
				}
				info, err := os.Stat(canonical)
				if err != nil || !info.IsDir() {
					return nil, fmt.Errorf("checkpoint source root %q is not a directory", logical)
				}
				physicalRoots[physical] = canonical
			}
			var selected *planCheckpointRoot
			for artifact, root := range bindings.SourceArtifacts {
				rel, err := filepath.Rel(root, canonical)
				if err != nil || !fs.ValidPath(filepath.ToSlash(rel)) {
					continue
				}
				if selected != nil {
					return nil, fmt.Errorf("checkpoint source root %q has ambiguous artifact ownership", logical)
				}
				selected = &planCheckpointRoot{Artifact: artifact, Path: filepath.ToSlash(rel)}
			}
			if selected == nil {
				return nil, fmt.Errorf("checkpoint source root %q is not a declared artifact", logical)
			}
			r.Roots[profile][logical] = *selected
		}
		entry.Roots = nil
		r.Graph.Profiles[profile] = entry
	}
	for output, value := range plan.projectedGeneratorInternalOutputs {
		r.ProjectedInternalOutputs = append(r.ProjectedInternalOutputs, planCheckpointOutput{output.producerID, output.slot, value})
	}
	slices.SortFunc(r.ProjectedInternalOutputs, func(a, b planCheckpointOutput) int {
		if c := strings.Compare(a.Producer, b.Producer); c != 0 {
			return c
		}
		return a.Slot - b.Slot
	})
	if err := r.validateBindings(bindings); err != nil {
		return nil, err
	}
	data, err := json.Marshal(r)
	if err != nil {
		return nil, err
	}
	if len(data) > MaxActionPlanSnapshotBytes {
		return nil, fmt.Errorf("action checkpoint exceeds byte budget")
	}
	return data, nil
}

func (r *actionPlanCheckpoint) validateBindings(b ActionPlanCheckpointBindings) error {
	if !maps.Equal(r.VirtualSourceRoots, b.VirtualSourceRoots) {
		return fmt.Errorf("action checkpoint differs from current virtual source bindings")
	}
	if r.Schema != actionPlanCheckpointSchema || r.Variant != b.Variant || r.Plan == nil || r.Graph.Profiles == nil {
		return fmt.Errorf("invalid action checkpoint schema, variant or plan")
	}
	if r.ChoiceDialect != b.ChoiceDialect {
		return fmt.Errorf("action checkpoint differs from current choice dialect")
	}
	if r.HostPkgConfigManifestIdentity != b.HostPkgConfigManifestIdentity {
		return fmt.Errorf("action checkpoint differs from current host pkg-config manifest")
	}
	if !maps.Equal(r.Plan.Toolsets, b.Toolsets) || !maps.Equal(r.ConfigValues, b.ConfigValues) || !maps.Equal(r.ConfigFiles, b.ConfigFiles) || !slices.Equal(r.ConfigSymbolUniverse, b.ConfigSymbolUniverse) || !slices.Equal(r.SourceArtifacts, slices.Sorted(maps.Keys(b.SourceArtifacts))) || !slices.Equal(r.Roles, b.ActionRoles) {
		return fmt.Errorf("action checkpoint differs from current source/config/tool bindings")
	}
	if !maps.Equal(r.SourceNamespaces, b.SourceNamespaces) || !maps.Equal(r.SourceNamespacePrefixes, b.SourceNamespacePrefixes) || !maps.Equal(r.ExactSourceNamespaces, b.ExactSourceNamespaces) || !maps.Equal(r.ExactSourcePaths, b.ExactSourcePaths) {
		return fmt.Errorf("action checkpoint differs from current source namespace routing")
	}
	contracts := map[KbuildActionRoleRef]CompactKbuildActionContract{}
	for _, entry := range r.Contracts {
		if _, exists := contracts[entry.Role]; exists {
			return fmt.Errorf("duplicate action checkpoint contract")
		}
		contracts[entry.Role] = entry.Contract
	}
	if !reflect.DeepEqual(contracts, b.ActionContracts) {
		return fmt.Errorf("action checkpoint differs from current action contracts")
	}
	seenChecks := map[string]bool{}
	for _, id := range r.ExecutionCheckRoots {
		if seenChecks[id] {
			return fmt.Errorf("action checkpoint repeats source check root %s", id)
		}
		seenChecks[id] = true
		node, found := compactKbuildPlanNode(r.Plan, id)
		if !found || len(node.Outputs) == 0 ||
			!compactKbuildAuthenticatedExecutionCheckCompletion(r.Plan, node, node.Outputs[0].ObservedPath) {
			return fmt.Errorf("action checkpoint source check root %s lacks an authenticated completion", id)
		}
	}
	return nil
}

// RestoreActionPlanCheckpoint binds a saved lowered graph to current source
// artifacts and configuration. The caller must bind its independently restored
// compiler scopes, then run the ordinary complete-cut replay/observed-source
// analysis/final sealing pipeline. This method grants none of those proofs.
func RestoreActionPlanCheckpoint(data []byte, bindings ActionPlanCheckpointBindings) (*ActionPlan, error) {
	if err := bindings.validate(); err != nil {
		return nil, err
	}
	if len(data) > MaxActionPlanSnapshotBytes {
		return nil, fmt.Errorf("action checkpoint exceeds byte budget")
	}
	var r actionPlanCheckpoint
	d := json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&r); err != nil {
		return nil, err
	}
	canonical, err := json.Marshal(r)
	if err != nil || !bytes.Equal(data, canonical) {
		return nil, fmt.Errorf("noncanonical action checkpoint")
	}
	if err := r.validateBindings(bindings); err != nil {
		return nil, err
	}
	if len(r.Roots) != len(r.Graph.Profiles) {
		return nil, fmt.Errorf("action checkpoint source profiles differ")
	}
	for name, profile := range r.Graph.Profiles {
		roots, ok := r.Roots[name]
		if !ok || len(profile.Roots) != 0 || name != profile.Name {
			return nil, fmt.Errorf("invalid action checkpoint source profile")
		}
		profile.Roots = map[string]string{}
		for logical, root := range roots {
			if root.Virtual {
				virtual, ok := bindings.VirtualSourceRoots[logical]
				if !ok || root.Artifact != logical || root.Path != "." {
					return nil, fmt.Errorf("invalid action checkpoint virtual source root")
				}
				profile.Roots[logical] = virtual
				continue
			}
			physical, ok := bindings.SourceArtifacts[root.Artifact]
			if !ok || logical == "" || !fs.ValidPath(root.Path) || strings.ContainsAny(root.Path, "\\\x00") {
				return nil, fmt.Errorf("invalid action checkpoint source root")
			}
			profile.Roots[logical] = filepath.Join(physical, filepath.FromSlash(root.Path))
		}
		r.Graph.Profiles[name] = profile
	}
	plan := r.Plan
	plan.selectionGraph = restorePlanCheckpointGraph(r.Graph)
	plan.compilerProbeInvocations, plan.compoundCompilerProbes = r.CompilerInvocations, r.CompoundCompilerProbes
	plan.projectedGeneratorValidations, plan.projectedGeneratorInternalNodes = r.ProjectedValidations, r.ProjectedInternalNodes
	plan.executionCheckRoots = slices.Clone(r.ExecutionCheckRoots)
	plan.projectedGeneratorOriginalOutputs = r.ProjectedOriginalOutputs
	if r.ProjectedInternalOutputs != nil {
		plan.projectedGeneratorInternalOutputs = map[actionPlanOutputRef]bool{}
	}
	for _, output := range r.ProjectedInternalOutputs {
		key := actionPlanOutputRef{output.Producer, output.Slot}
		if _, exists := plan.projectedGeneratorInternalOutputs[key]; exists {
			return nil, fmt.Errorf("duplicate projected checkpoint output")
		}
		plan.projectedGeneratorInternalOutputs[key] = output.Value
	}
	configPaths, err := NativeConfigProjectionPaths(r.ConfigFiles)
	if err != nil {
		return nil, err
	}
	m := &CompactMetadata{
		configProjectionPaths: configPaths,
		configFragment:        r.ConfigValues, configSymbolUniverse: r.ConfigSymbolUniverse,
		sourceNamespaces: r.SourceNamespaces, sourceNamespacePrefixes: r.SourceNamespacePrefixes,
		exactSourceNamespaces: r.ExactSourceNamespaces, exactSourcePaths: r.ExactSourcePaths,
		actionContracts: map[KbuildActionRoleRef]CompactKbuildActionContract{},
	}
	seen := map[string]bool{}
	for _, name := range r.Profiles {
		profile, ok := plan.selectionGraph.profiles[name]
		if !ok || seen[name] {
			return nil, fmt.Errorf("invalid ordered checkpoint profile")
		}
		seen[name] = true
		m.Config.KbuildProfiles = append(m.Config.KbuildProfiles, profile)
	}
	if len(seen) != len(plan.selectionGraph.profiles) {
		return nil, fmt.Errorf("checkpoint profile ordering is incomplete")
	}
	for _, entry := range r.Contracts {
		m.actionContracts[entry.Role] = entry.Contract
	}
	m.actionRoles = r.Roles
	plan.metadata = m
	if err := validatePlanCheckpointGraph(plan, r.Graph); err != nil {
		return nil, err
	}
	// Projection lowering can change provisional node contents before the
	// normal final addressing pass. Validate a detached addressed copy, keeping
	// the live source-owner and compiler-projection keys provisional for replay.
	validation := cloneActionPlan(plan)
	if err := contentAddressActionPlanNodes(validation); err != nil {
		return nil, err
	}
	if err := validation.validateStructure(nil); err != nil {
		return nil, err
	}
	return plan, nil
}

func validateCheckpointReplay(plan *ActionPlan, options ActionPlanFamilyVariantPlanningOptions) error {
	if err := options.validate(); err != nil {
		return err
	}
	if options.Cut == nil {
		return fmt.Errorf("checkpoint replay requires the complete original family replay inputs")
	}
	if plan == nil || plan.metadata == nil || plan.selectionGraph == nil || len(plan.projectedGeneratorCandidates) != 0 {
		return fmt.Errorf("checkpoint replay requires a restored fully lowered plan")
	}
	m := plan.metadata
	if m.compilerPredefines == nil || m.compilerDefinedness == nil || m.compilerDollarPunctuation == nil || m.toolsetPathCapabilityNormalizer == nil {
		return fmt.Errorf("checkpoint replay requires current compiler scope bindings")
	}
	return nil
}

// ReplayActionPlanCheckpoint skips only Make evaluation and action lowering.
// It uses the same complete-cut verification, source scanner, final addressing,
// analysis seal and annotation collection as an ordinary fresh family replay.
func ReplayActionPlanCheckpoint(plan *ActionPlan, options ActionPlanFamilyVariantPlanningOptions) (*ActionPlanFamilyVariantPlanningResult, error) {
	if err := validateCheckpointReplay(plan, options); err != nil {
		return nil, err
	}
	prepared, err := analyzePreparedActionPlan(plan, true, options.Cache, &options)
	if err != nil {
		return nil, err
	}
	return finalizePreparedActionPlan(prepared, &options)
}

// DiscoverActionPlanCheckpointCompilerGuards uses the identical verified source
// analysis boundary without finalizing/publishing a family plan. The caller's
// callback installs the current round's supplemental answers and observer.
func DiscoverActionPlanCheckpointCompilerGuards(plan *ActionPlan, options ActionPlanFamilyVariantPlanningOptions) error {
	if err := validateCheckpointReplay(plan, options); err != nil {
		return err
	}
	if options.PrepareCompilerGuards == nil {
		return fmt.Errorf("checkpoint guard discovery requires a current compiler guard callback")
	}
	_, err := analyzePreparedActionPlan(plan, true, options.Cache, &options)
	return err
}
