package kconfig

import (
	"crypto/sha256"
	"fmt"
	"strings"

	"github.com/hermeticbuild/linux.bzl/internal/toolaction"
)

// CompactKbuildLinkVmlinuxSourceSpan is a half-open byte range in the
// immutable scripts/link-vmlinux.sh source. Its endpoints are line boundaries.
type CompactKbuildLinkVmlinuxSourceSpan struct {
	Start int
	End   int
}

// CompactKbuildLinkVmlinuxPhases records the two source-level Make boundaries
// and the shell effects which must execute on either side of them. The
// executable scripts are concatenations of the listed source spans; no shell
// commands are synthesized by the analyzer.
type CompactKbuildLinkVmlinuxPhases struct {
	SourceSHA256 string

	VersionScript string
	ObjectScript  string
	FinalScript   string
	VersionSpans  []CompactKbuildLinkVmlinuxSourceSpan
	ObjectSpans   []CompactKbuildLinkVmlinuxSourceSpan
	FinalSpans    []CompactKbuildLinkVmlinuxSourceSpan
}

type compactKbuildLinkScriptLine struct {
	start int
	end   int
	text  string
}

func compactKbuildLinkScriptLines(content string) []compactKbuildLinkScriptLine {
	lines := make([]compactKbuildLinkScriptLine, 0, strings.Count(content, "\n"))
	start := 0
	for start < len(content) {
		end := start + strings.IndexByte(content[start:], '\n') + 1
		lines = append(lines, compactKbuildLinkScriptLine{
			start: start, end: end, text: content[start : end-1],
		})
		start = end
	}
	return lines
}

func compactKbuildLinkScriptFunctionName(line string) (string, bool) {
	name, ok := strings.CutSuffix(line, "()")
	if !ok || name == "" {
		return "", false
	}
	for index := 0; index < len(name); index++ {
		ch := name[index]
		if ch == '_' || ch >= 'a' && ch <= 'z' || index != 0 && ch >= '0' && ch <= '9' {
			continue
		}
		return "", false
	}
	return name, true
}

func compactKbuildLinkScriptPrelude(lines []compactKbuildLinkScriptLine, end int) error {
	if len(lines) == 0 || lines[0].text != "#!/bin/sh" {
		return fmt.Errorf("link-vmlinux.sh requires an exact #!/bin/sh header")
	}
	index := 1
	skipComments := func() {
		for index < end {
			line := strings.TrimSpace(lines[index].text)
			if line != "" && !strings.HasPrefix(line, "#") {
				break
			}
			index++
		}
	}
	expect := func(want string) error {
		skipComments()
		if index == end || strings.TrimSpace(lines[index].text) != want {
			got := "end of prelude"
			if index < end {
				got = fmt.Sprintf("line %d: %q", index+1, lines[index].text)
			}
			return fmt.Errorf("link-vmlinux.sh expected %q, got %s", want, got)
		}
		index++
		return nil
	}
	for _, statement := range []string{"set -e", `LD="$1"`, `KBUILD_LDFLAGS="$2"`, `LDFLAGS_vmlinux="$3"`} {
		if err := expect(statement); err != nil {
			return err
		}
	}

	functions := map[string]bool{}
	linkerFound := false
	for {
		skipComments()
		if index == end {
			return fmt.Errorf("link-vmlinux.sh prelude omits its verbosity guard")
		}
		line := strings.TrimSpace(lines[index].text)
		if line == `case "${KBUILD_VERBOSE}" in` {
			break
		}
		if line == "trap on_exit EXIT" && functions["on_exit"] ||
			line == "trap on_signals HUP INT QUIT TERM" && functions["on_signals"] {
			index++
			continue
		}
		name, ok := compactKbuildLinkScriptFunctionName(line)
		if !ok || functions[name] {
			return fmt.Errorf("link-vmlinux.sh prelude has unsupported statement at line %d: %q", index+1, lines[index].text)
		}
		functions[name] = true
		index++
		if err := expect("{"); err != nil {
			return fmt.Errorf("link-vmlinux.sh function %q: %w", name, err)
		}
		for index < end && strings.TrimSpace(lines[index].text) != "}" {
			statement := strings.TrimSpace(lines[index].text)
			if statement == "{" || strings.Contains(statement, "<<") {
				return fmt.Errorf("link-vmlinux.sh function %q has unsupported syntax on line %d", name, index+1)
			}
			if name == "modpost_link" && strings.HasPrefix(statement, "${LD} ${KBUILD_LDFLAGS} -r -o ${1} ") && strings.HasSuffix(statement, " ${objects}") {
				if linkerFound {
					return fmt.Errorf("link-vmlinux.sh modpost_link contains multiple linker writes")
				}
				linkerFound = true
			}
			index++
		}
		if err := expect("}"); err != nil {
			return fmt.Errorf("link-vmlinux.sh function %q: %w", name, err)
		}
	}
	if !functions["modpost_link"] || !functions["objtool_link"] || !functions["cleanup"] ||
		!functions["vmlinux_link"] || !linkerFound {
		return fmt.Errorf("link-vmlinux.sh prelude does not define the vmlinux.o linker, objtool, final linker, and cleanup functions")
	}
	for _, statement := range []string{
		`case "${KBUILD_VERBOSE}" in`, "*1*)", "set -x", ";;", "esac",
		`if [ "$1" = "clean" ]; then`, "cleanup", "exit 0", "fi",
		". include/config/auto.conf",
	} {
		if err := expect(statement); err != nil {
			return err
		}
	}
	// auto.conf is generated by Kconfig; its assignment grammar must be
	// validated at its own producer before treating this source statement as
	// safe to replay. This parser cannot prove arbitrary sourced file content.
	skipComments()
	if index != end {
		return fmt.Errorf("link-vmlinux.sh prelude has an effect after auto.conf at line %d", index+1)
	}
	return nil
}

func compactKbuildLinkScriptEffect(lines []compactKbuildLinkScriptLine, start, end int, want []string) error {
	step := 0
	for index := start; index < end; index++ {
		line := strings.TrimSpace(lines[index].text)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if step == len(want) || line != want[step] {
			return fmt.Errorf("link-vmlinux.sh unexpected phase effect at line %d: %q", index+1, lines[index].text)
		}
		step++
	}
	if step != len(want) {
		return fmt.Errorf("link-vmlinux.sh phase is incomplete: found %d of %d expected statements", step, len(want))
	}
	return nil
}

func compactKbuildLinkScriptSpans(content string, spans []CompactKbuildLinkVmlinuxSourceSpan) string {
	var script strings.Builder
	for _, span := range spans {
		script.WriteString(content[span.Start:span.End])
	}
	return script.String()
}

// ValidateCompactKbuildLinkVmlinuxAutoConf checks the actual config capsule
// before a link-vmlinux phase repeats its source-defined auto.conf import.
// Kconfig emits CONFIG_*=value assignments, but a double-quoted value
// containing $() or backticks would execute each time that file is sourced.
// The script source alone cannot establish this condition.
func ValidateCompactKbuildLinkVmlinuxAutoConf(contents string) error {
	return toolaction.ValidateStaticConfigAssignments(contents)
}

// AnalyzeCompactKbuildLinkVmlinuxPhases recognizes scripts whose first Make
// builds init after writing .version and whose second Make consumes vmlinux.o.
// A script without these old internal-output boundaries returns false. Once
// any boundary is present, a changed or unsafe shape is an error, not a
// reason to silently use the unsplit source script.
func AnalyzeCompactKbuildLinkVmlinuxPhases(content string) (CompactKbuildLinkVmlinuxPhases, bool, error) {
	const (
		initMake    = `${MAKE} -f "${srctree}/scripts/Makefile.build" obj=init need-builtin=1`
		modpostMake = `${MAKE} -f "${srctree}/scripts/Makefile.modpost" MODPOST_VMLINUX=1`
	)
	var zero CompactKbuildLinkVmlinuxPhases
	if content == "" || !strings.HasSuffix(content, "\n") || strings.ContainsAny(content, "\x00\r") {
		return zero, false, fmt.Errorf("link-vmlinux.sh source must contain complete LF-terminated lines")
	}
	lines := compactKbuildLinkScriptLines(content)
	version, firstMake, object, secondMake := -1, -1, -1, -1
	oldBoundary := false
	for index, line := range lines {
		statement := strings.TrimSpace(line.text)
		if strings.HasPrefix(statement, "#") {
			continue
		}
		switch statement {
		case "info GEN .version":
			oldBoundary = true
			if version != -1 {
				return zero, false, fmt.Errorf("link-vmlinux.sh has duplicate .version phase")
			}
			version = index
		case initMake:
			oldBoundary = true
			if firstMake != -1 {
				return zero, false, fmt.Errorf("link-vmlinux.sh has duplicate init Make boundary")
			}
			firstMake = index
		case "modpost_link vmlinux.o":
			oldBoundary = true
			if object != -1 {
				return zero, false, fmt.Errorf("link-vmlinux.sh has duplicate vmlinux.o link")
			}
			object = index
		case modpostMake:
			oldBoundary = true
			if secondMake != -1 {
				return zero, false, fmt.Errorf("link-vmlinux.sh has duplicate modpost Make boundary")
			}
			secondMake = index
		}
	}
	if !oldBoundary {
		return zero, false, nil
	}
	if version < 0 || firstMake < 0 || object < 0 || secondMake < 0 ||
		!(version < firstMake && firstMake < object && object < secondMake) {
		return zero, false, fmt.Errorf("link-vmlinux.sh requires ordered .version, init Make, vmlinux.o link, and modpost Make boundaries")
	}
	for index, line := range lines {
		statement := strings.TrimSpace(line.text)
		if strings.HasPrefix(statement, "#") {
			continue
		}
		if strings.Contains(statement, "${MAKE}") && index != firstMake && index != secondMake {
			return zero, false, fmt.Errorf("link-vmlinux.sh has an unrecognized Make invocation at line %d", index+1)
		}
	}
	if err := compactKbuildLinkScriptPrelude(lines, version); err != nil {
		return zero, false, err
	}
	if err := compactKbuildLinkScriptEffect(lines, version, firstMake, []string{
		"info GEN .version", "if [ -r .version ]; then", "VERSION=$(expr 0$(cat .version) + 1)",
		"echo $VERSION > .version", "else", "rm -f .version", "echo 1 > .version", "fi;",
	}); err != nil {
		return zero, false, err
	}
	objectEffects := []string{"modpost_link vmlinux.o", "objtool_link vmlinux.o"}
	for index := firstMake + 1; index < object; index++ {
		if strings.TrimSpace(lines[index].text) == "info LD vmlinux.o" {
			objectEffects = append([]string{"info LD vmlinux.o"}, objectEffects...)
			break
		}
	}
	if err := compactKbuildLinkScriptEffect(lines, firstMake+1, secondMake, objectEffects); err != nil {
		return zero, false, err
	}
	finalLinks := 0
	for _, line := range lines[secondMake+1:] {
		statement := strings.TrimSpace(line.text)
		if strings.HasPrefix(statement, "#") {
			continue
		}
		if strings.HasPrefix(statement, "vmlinux_link vmlinux ") {
			finalLinks++
		}
	}
	if finalLinks != 1 {
		return zero, false, fmt.Errorf("link-vmlinux.sh final phase must invoke the source-defined vmlinux linker once")
	}
	prelude := CompactKbuildLinkVmlinuxSourceSpan{Start: 0, End: lines[version].start}
	versionSpan := CompactKbuildLinkVmlinuxSourceSpan{Start: 0, End: lines[firstMake].start}
	objectSpan := CompactKbuildLinkVmlinuxSourceSpan{Start: lines[firstMake].end, End: lines[secondMake].start}
	finalSpan := CompactKbuildLinkVmlinuxSourceSpan{Start: lines[secondMake].end, End: len(content)}
	if finalSpan.Start == finalSpan.End {
		return zero, false, fmt.Errorf("link-vmlinux.sh final link phase is empty")
	}
	sum := sha256.Sum256([]byte(content))
	phases := CompactKbuildLinkVmlinuxPhases{
		SourceSHA256: fmt.Sprintf("%x", sum[:]),
		VersionSpans: []CompactKbuildLinkVmlinuxSourceSpan{versionSpan},
		ObjectSpans:  []CompactKbuildLinkVmlinuxSourceSpan{prelude, objectSpan},
		FinalSpans:   []CompactKbuildLinkVmlinuxSourceSpan{prelude, finalSpan},
	}
	phases.VersionScript = compactKbuildLinkScriptSpans(content, phases.VersionSpans)
	phases.ObjectScript = compactKbuildLinkScriptSpans(content, phases.ObjectSpans)
	phases.FinalScript = compactKbuildLinkScriptSpans(content, phases.FinalSpans)
	return phases, true, nil
}
