load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "pkgconfigshim_lib",
    srcs = ["main.go"],
    importpath = "github.com/hermeticbuild/linux.bzl/internal/cmd/pkgconfigshim",
    visibility = ["//visibility:private"],
    deps = ["//internal/pkgconfigmanifest"],
)

go_binary(
    name = "pkgconfigshim",
    embed = [":pkgconfigshim_lib"],
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "pkgconfigshim_test",
    srcs = ["main_test.go"],
    embed = [":pkgconfigshim_lib"],
)
